POST http://localhost:8080
Content-Type: text/plain

ya.ru

###
GET http://localhost:8080/lLUP9gLO


### /api/shorten
POST http://localhost:8080/api/shorten
Content-Type: application/json
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "url": "example.com"
}
