POST http://localhost:8080
Content-Type: text/plain

ya.ru

###
GET http://localhost:8080/tPFt2T6K

###
GET /OgeqAqt9 HTTP/1.1
Content-Type: application/json
Host: localhost:8080
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

### compressed with gzip
GET http://localhost:8080/2HKSVGqX
Content-Encoding: gzip

### /api/shorten
POST http://localhost:8080/api/shorten
Content-Type: application/json
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "url": "example.com"
}
